### ISSUE TITLE
格子大小调节

### ISSUE THREAD

**Issue by putianyi889** [darknessgod/whitemeow#10]
- [X] 支持格子大小调节
- [X] +-调节大小
- [X] 使用矢量图
- [x] ctrl+滚轮调节
- [ ] 快捷键调节时在界面醒目位置显示大小（比如增加一个状态栏显示通知）

**Comment by darknessgod** [comment]
现在的方案不够醒目吗

**Comment by putianyi889** [comment]
现在需要进菜单才能看到大小

**Comment by putianyi889** [comment]
剩下一个是UI的优化，我给单独分一类吧
