### ISSUE TITLE
UPK / Replay of a Board Resulting in New Board

### ISSUE THREAD

**Issue by LEBaldy** [darknessgod/whitemeow#22]
Upon pressing R to replay the board, I was presented with a different, but extremely similar board.

This is reproducible, but is not guaranteed. The current understanding of how and why the bug occurs is this:
> If you play a game and the first click would be a mine, then it moves it somewhere else. But when you upk, it has the board as it was before that mine was moved. 

https://user-images.githubusercontent.com/88564611/159567104-f2185b8f-8bff-4c99-8531-8d2a6f4c2e1b.mp4

**Comment by darknessgod** [comment]
fixed
